// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscm1maGAdr8c-hfYKGx8gD6JHc1hJps0',
    appId: '1:703696626484:android:c83efc8aa6dd740d66bb61',
    messagingSenderId: '703696626484',
    projectId: 'app-envio-rgw',
    storageBucket: 'app-envio-rgw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS27IIirzFcMVRTHjfEoriaqX_uUAl6ps',
    appId: '1:703696626484:ios:51e68034468fedc866bb61',
    messagingSenderId: '703696626484',
    projectId: 'app-envio-rgw',
    storageBucket: 'app-envio-rgw.firebasestorage.app',
    iosBundleId: 'com.example.appEnvio',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbovwzbdb-zSE1pIT5qM1iRVN5rcq04ag',
    appId: '1:703696626484:web:6de6405292adc4f466bb61',
    messagingSenderId: '703696626484',
    projectId: 'app-envio-rgw',
    authDomain: 'app-envio-rgw.firebaseapp.com',
    storageBucket: 'app-envio-rgw.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS27IIirzFcMVRTHjfEoriaqX_uUAl6ps',
    appId: '1:703696626484:ios:51e68034468fedc866bb61',
    messagingSenderId: '703696626484',
    projectId: 'app-envio-rgw',
    storageBucket: 'app-envio-rgw.firebasestorage.app',
    iosBundleId: 'com.example.appEnvio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbovwzbdb-zSE1pIT5qM1iRVN5rcq04ag',
    appId: '1:703696626484:web:df58b378fcaef06566bb61',
    messagingSenderId: '703696626484',
    projectId: 'app-envio-rgw',
    authDomain: 'app-envio-rgw.firebaseapp.com',
    storageBucket: 'app-envio-rgw.firebasestorage.app',
  );

}